version: "3.8"

services:
    # 1. The FastAPI Backend
    governed-ai-api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: governed-ai-api
        ports:
            - "8000:8000"
        env_file:
            - .env
        environment:
            - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/gcp-service-account-key.json
            - GRPC_DNS_RESOLVER=native
        volumes:
            - ./gcp-service-account-key.json:/app/credentials/gcp-service-account-key.json:ro
        restart: unless-stopped

    # 2. The React Frontend (Nginx)
    governed-ai-ui:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: governed-ai-ui
        ports:
            - "80:80" # Just type 'http://localhost' in your browser!
        depends_on:
            - governed-ai-api
        restart: unless-stopped
